### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Norbert515/flutter_sequence_animation#11]
I was trying to use the following
flutter_sequence_animation: "^4.0.0-nullsafety"

however it fails - seems the update is not published.

Do you plan to publish ?

**Comment by JonasKuschel** [comment]
I am also still waiting for the null-safety. When are you going to publish it?

**Comment by tmtong** [comment]
It is a shame that this project seems to be dead. Time to move on to something else

**Comment by Norbert515** [comment]
It's published now

**Comment by Abhijit-Revamp** [comment]
Thanks a ton

**Comment by Abhijit-Revamp** [comment]
Possible to remove the latest from "PreRelease"?
