### ISSUE TITLE
Offset/Delay parameter

### ISSUE THREAD

**Issue by modulovalue** [Norbert515/flutter_sequence_animation#2]
An offset or delay parameter for `addAnimatable` would be really useful.
i.e. if you'd want to delay an animation by a certain duration then providing a delay Duration would remove the need for adding a duration to the `from` and `to` values.

Edit: I also think it would be useful if the `SequenceAnimationBuilder` had a "global" delay that affected all animatables

**Comment by Norbert515** [comment]
I'm not 100% sure about this. If you'd want a delay you could first await a delayed Future. I think adding a delay would bloat the API because it can be done very easily by hand.
